include:
  - path: ../synapse/docker-compose.yml

services:
  bot:
    build:
      context: .
    restart: unless-stopped
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    depends_on:
      synapse:
        condition: service_healthy
    ports:
      - 9292:9292
